# Generated by Django 6.0.6 on 2026-06-06 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_supplier', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Supplier ID')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Legal name')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('tax_id', models.CharField(max_length=30, unique=True, verbose_name='Tax ID')),
                ('country', models.CharField(db_index=True, max_length=60, verbose_name='Country')),
                ('state_province', models.CharField(max_length=60, verbose_name='State/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact name')),
                ('contact_role', models.CharField(blank=True, max_length=150, verbose_name='Contact role')),
                ('category', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('service', 'Service Provider'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('payment_terms', models.CharField(choices=[('net_30', 'Net 30'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('cod', 'Cash on Delivery'), ('advance', 'Advance Payment')], default='net_30', max_length=50, verbose_name='Payment terms')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('credit_card', 'Credit Card')], default='bank_transfer', max_length=50, verbose_name='Payment method')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('MXN', 'Mexican Peso'), ('COP', 'Colombian Peso'), ('ARS', 'Argentine Peso')], default='USD', max_length=3, verbose_name='Currency')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Bank account')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'status'], name='suppliers_s_name_4fa57b_idx')],
            },
        ),
    ]
