# Generated by Django 6.0.6 on 2026-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='id_supplier',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Supplier ID'),
        ),
    ]
