# Generated by Django 6.0.6 on 2026-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Description'),
        ),
    ]
