# Generated by Django 6.0.6 on 2026-06-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0004_materialtype_unit_alter_material_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='materials.materialtype', verbose_name='Material Type'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='materials.unit', verbose_name='Unit'),
        ),
    ]
