# Generated by Django 6.0.6 on 2026-06-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_category_options'),
        ('materials', '0003_alter_material_id_material'),
        ('suppliers', '0003_alter_supplier_id_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('symbol', models.CharField(max_length=100, verbose_name='Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_purchase_order', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID Purchase Order')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Issue Date')),
                ('estimated_delivery_date', models.DateTimeField(verbose_name='Estimated Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='ID Supplier')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.orderstatus', verbose_name='Order Status')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='LinesPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_purchase_order_line', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID Purchase Order Line')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
                ('receive_quantity', models.IntegerField(verbose_name='Receive Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('currency_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency Supplier')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='Material ID')),
                ('unit_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.unit', verbose_name='Unit Type')),
                ('id_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Lines Purchase Order',
                'verbose_name_plural': 'Lines Purchase Orders',
            },
        ),
    ]
