# Generated by Django 6.0.6 on 2026-06-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linespurchaseorder',
            name='id_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_purchase_order', to='purchases.purchaseorder', verbose_name='Purchase Order'),
        ),
    ]
