# Generated by Django 6.0.6 on 2026-06-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorymovement_currency_inventorymovement_price'),
        ('materials', '0003_alter_material_id_material'),
        ('purchases', '0002_alter_linespurchaseorder_id_purchase_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=100, verbose_name='Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Goods Receipt Status',
                'verbose_name_plural': 'Goods Receipt Status',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_goods_receipt', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID Goods Receipts')),
                ('receipt_date', models.DateTimeField(verbose_name='Receipt Date')),
                ('supplier_delivery_note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier Delivery Note Ref')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('id_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseorder', verbose_name='ID Purchase Order')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.goodsreceiptstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Goods Receipt Status',
                'verbose_name_plural': 'Goods Receipt Status',
            },
        ),
        migrations.CreateModel(
            name='LinesGoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_goods_receipt_line', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID Goods Receipt Line')),
                ('receive_quantity', models.IntegerField(verbose_name='Receive Quantity')),
                ('inventory_movement_ref', models.CharField(blank=True, max_length=10, null=True, verbose_name='Inventory Movement ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('id_goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.goodsreceipt', verbose_name='ID Goods Receipts')),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.locationInventory', verbose_name='Destination Location')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='Material ID')),
                ('id_purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.linespurchaseorder', verbose_name='ID Purchase Order Line')),
                ('unit_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.unit', verbose_name='Unit Type')),
            ],
            options={
                'verbose_name': 'Lines Goods Receipt',
                'verbose_name_plural': 'Lines Goods Receipts',
            },
        ),
    ]
