# Generated by Django 6.0.6 on 2026-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_goodsreceiptstatus_goodsreceipt_linesgoodsreceipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceipt',
            options={'verbose_name': 'Goods Receipt', 'verbose_name_plural': 'Goods Receipt'},
        ),
        migrations.AlterField(
            model_name='linesgoodsreceipt',
            name='inventory_movement_ref',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inventory Movement ID'),
        ),
    ]
