# Generated by Django 6.0.6 on 2026-06-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options'),
        ('purchases', '0004_alter_goodsreceipt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linesgoodsreceipt',
            name='id_purchase_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.linespurchaseorder', verbose_name='ID Purchase Order Line'),
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=100, verbose_name='Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Invoice Status',
                'verbose_name_plural': 'Invoice Status',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_invoice', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID Invoice')),
                ('invoice_date', models.DateField(auto_now=True, verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Payment Due Date')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('currency_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('id_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseorder', verbose_name='ID Purchase Order')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.goodsreceiptstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
            },
        ),
        migrations.CreateModel(
            name='LinesPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_invoice_line', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID Invoice Line')),
                ('price', models.FloatField(verbose_name='Unit Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Invoiced Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('currency_invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('id_purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.linespurchaseorder', verbose_name='ID Purchase Order Line')),
                ('id_purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchases.purchaseinvoice', verbose_name='ID Purchase Invoice')),
            ],
            options={
                'verbose_name': 'Lines Purchase Invoice',
                'verbose_name_plural': 'Lines Purchase Invoices',
            },
        ),
    ]
