# Generated by Django 6.0.6 on 2026-06-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_linesgoodsreceipt_id_purchase_order_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.invoicestatus', verbose_name='Status'),
        ),
    ]
