# Generated by Django 6.0.6 on 2026-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
