# Generated by Django 6.0.6 on 2026-06-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'verbose_name': 'Inventory Movement', 'verbose_name_plural': 'Inventory Movements'},
        ),
    ]
