# Generated by Django 6.0.6 on 2026-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorymovement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='id_inventory_movement',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Inventory Movement ID'),
        ),
        migrations.AlterField(
            model_name='locationInventory',
            name='id_location',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Location ID'),
        ),
    ]
