# Generated by Django 6.0.6 on 2026-06-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options'),
        ('inventory', '0003_alter_inventorymovement_id_inventory_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        
    ]
