# Generated by Django 6.0.6 on 2026-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorymovement_currency_inventorymovement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=18, verbose_name='Exchange Rate'),
        ),
    ]
