# Generated by Django 6.0.6 on 2026-06-23 15:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorymovement_exchange_rate'),
        ('materials', '0003_alter_material_id_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Journal Date')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('avg_price_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('total_value_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.locationinventory', verbose_name='ID Location')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='ID Material')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('date', 'id_location', 'id_material')},
            },
        ),
    ]
