# Generated by Django 6.0.6 on 2026-06-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock'),
        ('materials', '0003_alter_material_id_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='materials.unit', verbose_name='Unit Type'),
            preserve_default=False,
        ),
    ]
