# Generated by Django 6.0.6 on 2026-06-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_customer', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Supplier ID')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Legal name')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('tax_id', models.CharField(max_length=30, unique=True, verbose_name='Tax ID')),
                ('state_province', models.CharField(max_length=60, verbose_name='State/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact name')),
                ('contact_role', models.CharField(blank=True, max_length=150, verbose_name='Contact role')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Bank account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Category')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
    ]
