# Generated by Django 6.0.6 on 2026-06-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod', verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.paymentterm', verbose_name='Payment terms'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'status'], name='customers_c_name_954a7c_idx'),
        ),
    ]
