# Generated by Django 6.0.6 on 2026-06-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
