# Generated by Django 6.0.6 on 2026-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
