# Generated by Django 6.0.6 on 2026-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_accountgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaccount',
            name='id_account',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='id_account_group',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Account Group ID'),
        ),
        migrations.AlterField(
            model_name='accountnature',
            name='id_account_nature',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Account Nature ID'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='id_account_type',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Account Type'),
        ),
    ]
