# Generated by Django 6.0.6 on 2026-06-20 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accountaccount_id_account_and_more'),
        ('core', '0002_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_journal', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Journal ID')),
                ('group_journal', models.CharField(max_length=10, verbose_name='Group Journal ID')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('credit', models.FloatField(default=0.0, verbose_name='Credit')),
                ('debit', models.FloatField(default=0.0, verbose_name='Debit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountaccount', verbose_name='Account ID')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
    ]
